# Generated by Django 5.2.7 on 2026-01-26 19:58

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lote_produccion', '0001_initial'),
        ('materia_prima', '0001_initial'),
        ('unidad', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialProduccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('used_quantity', models.DecimalField(decimal_places=4, help_text='Cantidad de materia prima utilizada en este lote', max_digits=12, verbose_name='Cantidad Usada')),
                ('costo_unitario', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), help_text='Costo promedio de la materia prima al momento de usarla', max_digits=12, verbose_name='Costo Unitario')),
                ('costo_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='used_quantity * costo_unitario', max_digits=15, verbose_name='Costo Total')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materiales', to='lote_produccion.loteproduccion', verbose_name='Lote de Producción')),
                ('raw_material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='materiales_produccion', to='materia_prima.materiaprima', verbose_name='Materia Prima')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='materiales_produccion', to='unidad.unidad', verbose_name='Unidad de Medida')),
            ],
            options={
                'verbose_name': 'Material de Producción',
                'verbose_name_plural': 'Materiales de Producción',
                'db_table': 'material_produccion',
                'ordering': ['-created_at'],
                'unique_together': {('batch', 'raw_material')},
            },
        ),
    ]
