# Generated by Django 5.2.7 on 2026-01-21 17:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lote_produccion', '0001_initial'),
        ('materia_prima', '0001_initial'),
        ('unidad', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialProduccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('used_quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materiales', to='lote_produccion.loteproduccion')),
                ('raw_material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='materiales_produccion', to='materia_prima.materiaprima')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='materiales_produccion', to='unidad.unidad')),
            ],
            options={
                'verbose_name': 'Material de Producción',
                'verbose_name_plural': 'Materiales de Producción',
                'db_table': 'material_produccion',
                'ordering': ['-created_at'],
            },
        ),
    ]
