# Generated by Django 5.2.7 on 2026-01-23 03:50

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lote_produccion', '0003_alter_loteproduccion_options_loteproduccion_almacen_and_more'),
        ('materia_prima', '0002_alter_materiaprima_stock'),
        ('material_produccion', '0001_initial'),
        ('unidad', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialproduccion',
            name='costo_total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='used_quantity * costo_unitario', max_digits=15, verbose_name='Costo Total'),
        ),
        migrations.AddField(
            model_name='materialproduccion',
            name='costo_unitario',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), help_text='Costo promedio de la materia prima al momento de usarla', max_digits=12, verbose_name='Costo Unitario'),
        ),
        migrations.AlterField(
            model_name='materialproduccion',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materiales', to='lote_produccion.loteproduccion', verbose_name='Lote de Producción'),
        ),
        migrations.AlterField(
            model_name='materialproduccion',
            name='raw_material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='materiales_produccion', to='materia_prima.materiaprima', verbose_name='Materia Prima'),
        ),
        migrations.AlterField(
            model_name='materialproduccion',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='materiales_produccion', to='unidad.unidad', verbose_name='Unidad de Medida'),
        ),
        migrations.AlterField(
            model_name='materialproduccion',
            name='used_quantity',
            field=models.DecimalField(decimal_places=4, help_text='Cantidad de materia prima utilizada en este lote', max_digits=12, verbose_name='Cantidad Usada'),
        ),
        migrations.AlterUniqueTogether(
            name='materialproduccion',
            unique_together={('batch', 'raw_material')},
        ),
    ]
