# Generated by Django 5.2.7 on 2026-01-05 03:03

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_code', models.CharField(help_text='Codigo unico de identificacion de la orden', max_length=50, unique=True, verbose_name='Codigo de Orden')),
                ('order_date', models.DateField(help_text='Fecha en que se realiza la orden', verbose_name='Fecha de Orden')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('confirmed', 'Confirmada'), ('in_progress', 'En Proceso'), ('completed', 'Completada'), ('cancelled', 'Cancelada')], default='pending', help_text='Estado actual de la orden', max_length=20, verbose_name='Estado')),
                ('notes', models.TextField(blank=True, help_text='Observaciones o instrucciones especiales', null=True, verbose_name='Notas')),
                ('tax_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Porcentaje de impuesto aplicado (ej: 15.00 para 15%)', max_digits=5, verbose_name='Tasa de Impuesto (%)')),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Monto calculado de impuestos (autocalculado)', max_digits=12, verbose_name='Monto de Impuesto')),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Monto total de la orden (autocalculado)', max_digits=12, verbose_name='Total de Orden')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creacion')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ultima Actualizacion')),
                ('client', models.ForeignKey(help_text='Cliente que realiza la orden', on_delete=django.db.models.deletion.PROTECT, related_name='ordenes', to='cliente.cliente', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Orden de Cliente',
                'verbose_name_plural': 'Órdenes de Cliente',
                'db_table': 'orden_cliente',
                'ordering': ['-order_date'],
            },
        ),
    ]
