# Generated by Django 5.2.7 on 2025-11-20 06:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cliente', '0003_remove_cliente_activo_cliente_nombre_contacto'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_code', models.CharField(max_length=50, unique=True)),
                ('order_date', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('confirmed', 'Confirmada'), ('in_progress', 'En Proceso'), ('completed', 'Completada'), ('cancelled', 'Cancelada')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordenes', to='cliente.cliente')),
            ],
            options={
                'verbose_name': 'Orden de Cliente',
                'verbose_name_plural': 'Órdenes de Cliente',
                'db_table': 'orden_cliente',
                'ordering': ['-order_date'],
            },
        ),
    ]
