# Generated by Django 5.2.7 on 2025-12-17 03:49

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0003_remove_cliente_activo_cliente_nombre_contacto'),
        ('orden_cliente', '0002_ordencliente_tax_amount_ordencliente_tax_rate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordencliente',
            name='client',
            field=models.ForeignKey(help_text='Cliente que realiza la orden', on_delete=django.db.models.deletion.PROTECT, related_name='ordenes', to='cliente.cliente', verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='ordencliente',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creacion'),
        ),
        migrations.AlterField(
            model_name='ordencliente',
            name='notes',
            field=models.TextField(blank=True, help_text='Observaciones o instrucciones especiales', null=True, verbose_name='Notas'),
        ),
        migrations.AlterField(
            model_name='ordencliente',
            name='order_code',
            field=models.CharField(help_text='Codigo unico de identificacion de la orden', max_length=50, unique=True, verbose_name='Codigo de Orden'),
        ),
        migrations.AlterField(
            model_name='ordencliente',
            name='order_date',
            field=models.DateField(help_text='Fecha en que se realiza la orden', verbose_name='Fecha de Orden'),
        ),
        migrations.AlterField(
            model_name='ordencliente',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('confirmed', 'Confirmada'), ('in_progress', 'En Proceso'), ('completed', 'Completada'), ('cancelled', 'Cancelada')], default='pending', help_text='Estado actual de la orden', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='ordencliente',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Monto calculado de impuestos (autocalculado)', max_digits=12, verbose_name='Monto de Impuesto'),
        ),
        migrations.AlterField(
            model_name='ordencliente',
            name='tax_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Porcentaje de impuesto aplicado (ej: 15.00 para 15%)', max_digits=5, verbose_name='Tasa de Impuesto (%)'),
        ),
        migrations.AlterField(
            model_name='ordencliente',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Monto total de la orden (autocalculado)', max_digits=12, verbose_name='Total de Orden'),
        ),
        migrations.AlterField(
            model_name='ordencliente',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Ultima Actualizacion'),
        ),
    ]
