# Generated by Django 5.2.7 on 2026-01-21 07:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("almacen", "0001_initial"),
        ("materia_prima", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RecepcionMaterial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cantidad",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Cantidad total recibida",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "costo_unitario",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Costo unitario por unidad de materia prima",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "total",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Total de la recepción (cantidad × costo_unitario)",
                        max_digits=14,
                        null=True,
                    ),
                ),
                (
                    "proveedor",
                    models.CharField(
                        blank=True,
                        help_text="Nombre del proveedor",
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "fecha_de_recepcion",
                    models.DateField(
                        blank=True,
                        help_text="Fecha en que se recibió el material",
                        null=True,
                    ),
                ),
                (
                    "numero_de_factura",
                    models.CharField(
                        blank=True,
                        help_text="Número de factura del proveedor",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "observaciones",
                    models.TextField(
                        blank=True,
                        help_text="Observaciones generales de la recepción",
                        null=True,
                    ),
                ),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True)),
                (
                    "almacen",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recepciones_material",
                        to="almacen.almacen",
                    ),
                ),
                (
                    "materia_prima",
                    models.ForeignKey(
                        blank=True,
                        help_text="Materia prima principal de esta recepción",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="recepciones_principales",
                        to="materia_prima.materiaprima",
                    ),
                ),
            ],
            options={
                "verbose_name": "Recepción de Material",
                "verbose_name_plural": "Recepciones de Material",
                "db_table": "recepcion_material",
                "ordering": ["-fecha_de_recepcion"],
                "indexes": [
                    models.Index(
                        fields=["materia_prima"], name="recepcion_m_materia_bd9067_idx"
                    ),
                    models.Index(
                        fields=["proveedor"], name="recepcion_m_proveed_5bd71c_idx"
                    ),
                    models.Index(
                        fields=["numero_de_factura"],
                        name="recepcion_m_numero__8ba994_idx",
                    ),
                    models.Index(
                        fields=["-fecha_de_recepcion"],
                        name="recepcion_m_fecha_d_243864_idx",
                    ),
                ],
            },
        ),
    ]
