# Generated by Django 5.2.7 on 2026-01-05 07:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('almacen', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecepcionMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_recepcion', models.DateTimeField(auto_now_add=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('id_almacen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recepciones_material', to='almacen.almacen')),
            ],
        ),
    ]
