# Generated by Django 5.2.7 on 2026-01-21 05:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0001_initial'),
        ('materia_prima', '0002_materiaprima_costo_promedio'),
        ('recepcion_material', '0002_add_temp_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recepcionmaterial',
            options={'ordering': ['-fecha_de_recepcion'], 'verbose_name': 'Recepción de Material', 'verbose_name_plural': 'Recepciones de Material'},
        ),
        migrations.AlterField(
            model_name='recepcionmaterial',
            name='almacen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recepciones_material', to='almacen.almacen'),
        ),
        migrations.AlterField(
            model_name='recepcionmaterial',
            name='observaciones',
            field=models.TextField(blank=True, help_text='Observaciones generales de la recepción', null=True),
        ),
        migrations.AddIndex(
            model_name='recepcionmaterial',
            index=models.Index(fields=['materia_prima'], name='recepcion_m_materia_bd9067_idx'),
        ),
        migrations.AddIndex(
            model_name='recepcionmaterial',
            index=models.Index(fields=['proveedor'], name='recepcion_m_proveed_5bd71c_idx'),
        ),
        migrations.AddIndex(
            model_name='recepcionmaterial',
            index=models.Index(fields=['numero_de_factura'], name='recepcion_m_numero__8ba994_idx'),
        ),
        migrations.AddIndex(
            model_name='recepcionmaterial',
            index=models.Index(fields=['-fecha_de_recepcion'], name='recepcion_m_fecha_d_243864_idx'),
        ),
        migrations.AlterModelTable(
            name='recepcionmaterial',
            table='recepcion_material',
        ),
    ]
