# Generated by Django 5.2.7 on 2026-01-23 11:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Archivo',
            fields=[
                ('archivo_id', models.CharField(editable=False, help_text='Codigo unico autogenerado (formato: ARC000001)', max_length=9, primary_key=True, serialize=False, verbose_name='ID Archivo')),
                ('nombre', models.CharField(help_text='Nombre descriptivo del PDF (ej: Reporte_Inventario_2025-11-15.pdf)', max_length=255, verbose_name='Nombre del Archivo')),
                ('tipo_reporte', models.CharField(choices=[('inventario', 'Inventario'), ('clientes', 'Clientes'), ('proveedores', 'Proveedores'), ('pedidos', 'Pedidos de Material'), ('materias_primas', 'Materias Primas'), ('ordenes', 'Ordenes de Cliente'), ('categorias', 'Categorias'), ('otro', 'Otro')], help_text='Categoria del reporte generado', max_length=30, verbose_name='Tipo de Reporte')),
                ('google_drive_id', models.CharField(help_text='ID del archivo en Google Drive', max_length=255, unique=True, verbose_name='Google Drive ID')),
                ('url_descarga', models.URLField(help_text='URL directa para descargar el archivo desde Google Drive', max_length=500, verbose_name='URL de Descarga')),
                ('tamaño', models.BigIntegerField(help_text='Tamaño del archivo en bytes', verbose_name='Tamaño')),
                ('descripcion', models.TextField(blank=True, help_text='Descripcion opcional del contenido del reporte', null=True, verbose_name='Descripcion')),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Generacion')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Ultima Actualizacion')),
                ('usuario_generador', models.ForeignKey(blank=True, help_text='Usuario que subio el archivo', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archivos_generados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Generador')),
            ],
            options={
                'verbose_name': 'Archivo',
                'verbose_name_plural': 'Archivos',
                'db_table': 'archivo',
                'ordering': ['-fecha_generacion'],
                'indexes': [models.Index(fields=['tipo_reporte'], name='archivo_tipo_re_589ac2_idx'), models.Index(fields=['fecha_generacion'], name='archivo_fecha_g_822f1b_idx'), models.Index(fields=['usuario_generador'], name='archivo_usuario_777690_idx')],
            },
        ),
    ]
