# Generated by Django 5.2.7 on 2026-01-21 17:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archivos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.DeleteModel(
            name='ArchivoIndex',
        ),
        migrations.AddIndex(
            model_name='archivo',
            index=models.Index(fields=['tipo_reporte'], name='archivo_tipo_re_589ac2_idx'),
        ),
        migrations.AddIndex(
            model_name='archivo',
            index=models.Index(fields=['fecha_generacion'], name='archivo_fecha_g_822f1b_idx'),
        ),
        migrations.AddIndex(
            model_name='archivo',
            index=models.Index(fields=['usuario_generador'], name='archivo_usuario_777690_idx'),
        ),
    ]
