# Generated by Django 5.2.7 on 2026-01-21 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archivos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivo',
            name='tipo_reporte',
            field=models.CharField(choices=[('inventario', 'Inventario'), ('clientes', 'Clientes'), ('proveedores', 'Proveedores'), ('pedidos', 'Pedidos de Material'), ('materias_primas', 'Materias Primas'), ('ordenes', 'Ordenes de Cliente'), ('categorias', 'Categorias'), ('otro', 'Otro')], help_text='Categoria del reporte generado', max_length=30, verbose_name='Tipo de Reporte'),
        ),
    ]
