# Generated by Django 5.2.7 on 2026-01-23 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archivos', '0002_delete_archivoindex_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivo',
            name='tipo_reporte',
            field=models.CharField(help_text='Categoria del reporte generado', max_length=30, verbose_name='Tipo de Reporte'),
        ),
    ]
