# Generated by Django 5.2.7 on 2025-12-09 02:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('unidad', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MateriaPrima',
            fields=[
                ('materia_prima_id', models.CharField(editable=False, help_text='Codigo unico autogenerado (formato: MP000001)', max_length=8, primary_key=True, serialize=False, verbose_name='ID Materia Prima')),
                ('nombre', models.CharField(help_text='Nombre de la materia prima (ej: Acido Sulfurico)', max_length=100, verbose_name='Nombre')),
                ('codigo', models.CharField(help_text='Codigo interno/SKU de la materia prima (ej: AC-SUL-98)', max_length=50, unique=True, verbose_name='Codigo')),
                ('descripcion', models.TextField(blank=True, help_text='Descripcion detallada, especificaciones tecnicas, pureza, etc', null=True, verbose_name='Descripcion')),
                ('densidad', models.DecimalField(blank=True, decimal_places=4, help_text='Densidad de la materia prima en g/cm3 o kg/L (opcional)', max_digits=10, null=True, verbose_name='Densidad')),
                ('stock_minimo', models.DecimalField(decimal_places=2, default=0, help_text='Cantidad minima requerida en inventario', max_digits=10, verbose_name='Stock Minimo')),
                ('stock_maximo', models.DecimalField(blank=True, decimal_places=2, help_text='Cantidad maxima permitida en inventario (opcional)', max_digits=10, null=True, verbose_name='Stock Maximo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creacion')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Ultima Actualizacion')),
                ('unidad_id', models.ForeignKey(help_text='Unidad en que se mide (kg, litros, etc)', on_delete=django.db.models.deletion.PROTECT, to='unidad.unidad', verbose_name='Unidad de Medida')),
            ],
            options={
                'verbose_name': 'Materia Prima',
                'verbose_name_plural': 'Materias Primas',
                'db_table': 'materia_prima',
                'ordering': ['materia_prima_id'],
                'indexes': [models.Index(fields=['codigo'], name='materia_pri_codigo_988ab7_idx'), models.Index(fields=['nombre'], name='materia_pri_nombre_567e35_idx')],
            },
        ),
    ]
