# Generated by Django 5.2.7 on 2025-12-11 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materia_prima', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materiaprima',
            name='stock_maximo',
        ),
        migrations.RemoveField(
            model_name='materiaprima',
            name='stock_minimo',
        ),
        migrations.AddField(
            model_name='materiaprima',
            name='stock',
            field=models.PositiveIntegerField(default=0, help_text='Cantidad actual disponible (unidades/paquetes, entero)', verbose_name='Stock'),
        ),
    ]
