# Generated by Django 5.2.7 on 2026-01-05 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materia_prima', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='materiaprima',
            name='costo_promedio',
            field=models.DecimalField(decimal_places=4, default=0.0, help_text='Costo promedio unitario actualizado por el Kardex', max_digits=12, verbose_name='Costo Promedio ($)'),
        ),
    ]
