# Generated by Django 5.2.7 on 2026-01-05 07:23

from django.db import migrations, models
from django.db import connection


def add_costo_promedio_if_not_exists(apps, schema_editor):
    """Agrega la columna costo_promedio solo si no existe"""
    with connection.cursor() as cursor:
        # Verificar si la columna ya existe
        cursor.execute("""
            SELECT column_name 
            FROM information_schema.columns 
            WHERE table_name='materia_prima' 
            AND column_name='costo_promedio';
        """)
        exists = cursor.fetchone()
        
        # Solo agregar si no existe
        if not exists:
            cursor.execute("""
                ALTER TABLE "materia_prima" 
                ADD COLUMN "costo_promedio" numeric(12, 4) DEFAULT 0 NOT NULL;
            """)


class Migration(migrations.Migration):

    dependencies = [
        ('materia_prima', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_costo_promedio_if_not_exists, migrations.RunPython.noop),
    ]
