# Generated by Django 5.2.7 on 2026-01-23 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materia_prima', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materiaprima',
            name='stock',
            field=models.DecimalField(decimal_places=4, default=0, help_text='Cantidad actual disponible', max_digits=12, verbose_name='Stock'),
        ),
    ]
