# Generated by Django 5.2.7 on 2026-01-04 21:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categoria', '0001_initial'),
        ('materia_prima', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='materiaprima',
            name='categoria_id',
            field=models.ForeignKey(default=1, help_text='Categoria de clasificacion de la materia prima', limit_choices_to={'tipo': 'RAW_MATERIAL'}, on_delete=django.db.models.deletion.PROTECT, related_name='materias_primas', to='categoria.categoria', verbose_name='Categoria'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='materiaprima',
            name='costo_promedio',
            field=models.DecimalField(decimal_places=4, default=0.0, help_text='Costo promedio unitario actualizado por el Kardex', max_digits=12, verbose_name='Costo Promedio ($)'),
        ),
    ]
