# Generated by Django 5.2.7 on 2026-01-08 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materia_prima', '0002_remove_materiaprima_stock_maximo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='materiaprima',
            name='stock_maximo',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Cantidad maxima permitida en inventario (opcional)', max_digits=10, null=True, verbose_name='Stock Maximo'),
        ),
        migrations.AddField(
            model_name='materiaprima',
            name='stock_minimo',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Cantidad minima requerida en inventario', max_digits=10, verbose_name='Stock Minimo'),
        ),
    ]
