# Generated by Django 5.2.7 on 2026-01-23 08:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materia_prima', '0003_alter_materiaprima_stock_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materiaprima',
            name='stock',
            field=models.DecimalField(decimal_places=6, default=0, help_text='Cantidad actual disponible', max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Stock'),
        ),
        migrations.AlterField(
            model_name='materiaprima',
            name='stock_maximo',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Cantidad maxima permitida en inventario (opcional)', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Stock Maximo'),
        ),
        migrations.AlterField(
            model_name='materiaprima',
            name='stock_minimo',
            field=models.DecimalField(decimal_places=6, default=0, help_text='Cantidad minima requerida en inventario', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Stock Minimo'),
        ),
    ]
