# Generated by Django 5.2.7 on 2026-01-23 11:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("proveedor", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PedidoMaterial",
            fields=[
                (
                    "pedido_material_id",
                    models.CharField(
                        editable=False,
                        help_text="Codigo unico autogenerado (formato: PM000001)",
                        max_length=8,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID Pedido Material",
                    ),
                ),
                (
                    "fecha_pedido",
                    models.DateField(
                        help_text="Fecha en que se realizo el pedido al proveedor",
                        verbose_name="Fecha del Pedido",
                    ),
                ),
                (
                    "fecha_entrega_esperada",
                    models.DateField(
                        blank=True,
                        help_text="Fecha estimada de llegada del pedido",
                        null=True,
                        verbose_name="Fecha de Entrega Esperada",
                    ),
                ),
                (
                    "numero_orden_compra",
                    models.CharField(
                        blank=True,
                        help_text="Numero de OC externo o del sistema contable",
                        max_length=50,
                        null=True,
                        verbose_name="Numero de Orden de Compra",
                    ),
                ),
                (
                    "observaciones",
                    models.TextField(
                        blank=True,
                        help_text="Notas o comentarios sobre el pedido",
                        null=True,
                        verbose_name="Observaciones",
                    ),
                ),
                (
                    "fecha_creacion",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Creacion"
                    ),
                ),
                (
                    "fecha_actualizacion",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Ultima Actualizacion"
                    ),
                ),
                (
                    "proveedor_id",
                    models.ForeignKey(
                        help_text="Proveedor al que se le solicito el material",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="proveedor.proveedor",
                        verbose_name="Proveedor",
                    ),
                ),
                (
                    "usuario_registro",
                    models.ForeignKey(
                        help_text="Empleado que registro el pedido en el sistema",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pedidos_materiales",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario que Registro",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pedido de Material",
                "verbose_name_plural": "Pedidos de Materiales",
                "db_table": "pedido_material",
                "ordering": ["-fecha_pedido", "-pedido_material_id"],
                "indexes": [
                    models.Index(
                        fields=["proveedor_id"], name="pedido_mate_proveed_339f27_idx"
                    ),
                    models.Index(
                        fields=["fecha_pedido"], name="pedido_mate_fecha_p_9e0141_idx"
                    ),
                    models.Index(
                        fields=["usuario_registro"],
                        name="pedido_mate_usuario_d35162_idx",
                    ),
                ],
            },
        ),
    ]
