# Generated by Django 5.2.7 on 2026-01-21 17:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pedido_material', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidomaterial',
            name='usuario_registro',
            field=models.ForeignKey(help_text='Empleado que registro el pedido en el sistema', on_delete=django.db.models.deletion.PROTECT, related_name='pedidos_materiales', to=settings.AUTH_USER_MODEL, verbose_name='Usuario que Registro'),
        ),
        migrations.AddIndex(
            model_name='pedidomaterial',
            index=models.Index(fields=['proveedor_id'], name='pedido_mate_proveed_339f27_idx'),
        ),
        migrations.AddIndex(
            model_name='pedidomaterial',
            index=models.Index(fields=['fecha_pedido'], name='pedido_mate_fecha_p_9e0141_idx'),
        ),
        migrations.AddIndex(
            model_name='pedidomaterial',
            index=models.Index(fields=['usuario_registro'], name='pedido_mate_usuario_d35162_idx'),
        ),
    ]
