# Generated by Django 5.2.7 on 2025-11-20 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_entrega', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(max_length=255)),
                ('observaciones', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
