# Generated by Django 5.2.7 on 2026-01-21 17:32

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orden_cliente', '0001_initial'),
        ('producto', '0001_initial'),
        ('unidad', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(help_text='Cantidad de envases del producto', verbose_name='Cantidad')),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Subtotal del item (quantity * precio, autocalculado)', max_digits=12, verbose_name='Subtotal')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creacion')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ultima Actualizacion')),
                ('order', models.ForeignKey(help_text='Orden a la que pertenece este item', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orden_cliente.ordencliente', verbose_name='Orden')),
                ('product', models.ForeignKey(help_text='Producto solicitado en este item', on_delete=django.db.models.deletion.PROTECT, related_name='orden_items', to='producto.producto', verbose_name='Producto')),
                ('unit', models.ForeignKey(help_text='Unidad de medida del producto (se hereda del producto)', on_delete=django.db.models.deletion.PROTECT, related_name='orden_items', to='unidad.unidad', verbose_name='Unidad de Medida')),
            ],
            options={
                'verbose_name': 'Orden Item',
                'verbose_name_plural': 'Orden Items',
                'db_table': 'orden_item',
                'ordering': ['-created_at'],
            },
        ),
    ]
