# Generated by Django 5.2.7 on 2025-11-20 06:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orden_item', '0001_initial'),
        ('producto', '0001_initial'),
        ('unidad', '0002_alter_unidad_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orden_items', to='producto.producto'),
        ),
        migrations.AddField(
            model_name='ordenitem',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orden_items', to='unidad.unidad'),
        ),
    ]
