# Generated by Django 5.2.7 on 2025-12-10 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orden_item', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenitem',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
