# Generated by Django 5.2.7 on 2025-12-10 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orden_item', '0003_ordenitem_subtotal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordenitem',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
    ]
