# Generated by Django 5.2.7 on 2025-12-17 03:49

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orden_cliente', '0003_alter_ordencliente_client_and_more'),
        ('orden_item', '0004_alter_ordenitem_quantity'),
        ('producto', '0003_producto_stock'),
        ('unidad', '0003_alter_unidad_options_unidad_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordenitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creacion'),
        ),
        migrations.AlterField(
            model_name='ordenitem',
            name='order',
            field=models.ForeignKey(help_text='Orden a la que pertenece este item', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orden_cliente.ordencliente', verbose_name='Orden'),
        ),
        migrations.AlterField(
            model_name='ordenitem',
            name='product',
            field=models.ForeignKey(help_text='Producto solicitado en este item', on_delete=django.db.models.deletion.PROTECT, related_name='orden_items', to='producto.producto', verbose_name='Producto'),
        ),
        migrations.AlterField(
            model_name='ordenitem',
            name='quantity',
            field=models.PositiveIntegerField(help_text='Cantidad de envases del producto', verbose_name='Cantidad'),
        ),
        migrations.AlterField(
            model_name='ordenitem',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Subtotal del item (quantity * precio, autocalculado)', max_digits=12, verbose_name='Subtotal'),
        ),
        migrations.AlterField(
            model_name='ordenitem',
            name='unit',
            field=models.ForeignKey(help_text='Unidad de medida del producto (se hereda del producto)', on_delete=django.db.models.deletion.PROTECT, related_name='orden_items', to='unidad.unidad', verbose_name='Unidad de Medida'),
        ),
        migrations.AlterField(
            model_name='ordenitem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Ultima Actualizacion'),
        ),
    ]
