# Generated by Django 5.2.7 on 2026-01-21 07:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("almacen", "0001_initial"),
        ("materia_prima", "0001_initial"),
        ("unidad", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="InventarioMaterial",
            fields=[
                (
                    "inventario_material_id",
                    models.CharField(
                        editable=False,
                        help_text="Codigo unico autogenerado (formato: IM000001)",
                        max_length=8,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID Inventario Material",
                    ),
                ),
                (
                    "cantidad",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Cantidad actual en stock",
                        max_digits=10,
                        verbose_name="Cantidad Disponible",
                    ),
                ),
                (
                    "fecha_creacion",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Creacion"
                    ),
                ),
                (
                    "fecha_actualizacion",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Ultima Actualizacion"
                    ),
                ),
                (
                    "almacen_id",
                    models.ForeignKey(
                        help_text="Ubicacion fisica donde esta el material",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="almacen.almacen",
                        verbose_name="Almacen",
                    ),
                ),
                (
                    "materia_prima_id",
                    models.ForeignKey(
                        help_text="Material que se esta inventariando",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="materia_prima.materiaprima",
                        verbose_name="Materia Prima",
                    ),
                ),
                (
                    "unidad_id",
                    models.ForeignKey(
                        help_text="Unidad en que se mide la cantidad (kg, litros, etc)",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="unidad.unidad",
                        verbose_name="Unidad de Medida",
                    ),
                ),
            ],
            options={
                "verbose_name": "Inventario de Material",
                "verbose_name_plural": "Inventarios de Materiales",
                "db_table": "inventario_material",
                "ordering": ["inventario_material_id"],
                "indexes": [
                    models.Index(
                        fields=["materia_prima_id"],
                        name="inventario__materia_d4decf_idx",
                    ),
                    models.Index(
                        fields=["almacen_id"], name="inventario__almacen_bbe563_idx"
                    ),
                ],
                "unique_together": {("materia_prima_id", "almacen_id")},
            },
        ),
    ]
