# Generated by Django 5.2.7 on 2026-01-26 19:58

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('almacen', '0001_initial'),
        ('producto', '0001_initial'),
        ('unidad', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoteProduccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_code', models.CharField(max_length=50, unique=True, verbose_name='Código de Lote')),
                ('production_date', models.DateField(verbose_name='Fecha de Producción')),
                ('produced_quantity', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='Cantidad Producida')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('in_progress', 'En Proceso'), ('completed', 'Completado'), ('cancelled', 'Cancelado')], default='pending', max_length=20, verbose_name='Estado')),
                ('costo_materiales', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Suma de costos de todas las materias primas usadas', max_digits=15, verbose_name='Costo de Materiales')),
                ('costo_unitario_producto', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), help_text='costo_materiales / produced_quantity', max_digits=12, verbose_name='Costo Unitario del Producto')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Completado')),
                ('almacen', models.ForeignKey(help_text='Almacén donde se fabrica y se registra el inventario', on_delete=django.db.models.deletion.PROTECT, related_name='lotes_produccion', to='almacen.almacen', verbose_name='Almacén')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lotes_produccion', to='producto.producto', verbose_name='Producto a Fabricar')),
                ('production_manager', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lotes_gestionados', to=settings.AUTH_USER_MODEL, verbose_name='Responsable de Producción')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lotes_produccion', to='unidad.unidad', verbose_name='Unidad de Medida')),
            ],
            options={
                'verbose_name': 'Lote de Producción',
                'verbose_name_plural': 'Lotes de Producción',
                'db_table': 'lote_produccion',
                'ordering': ['-production_date', '-created_at'],
                'indexes': [models.Index(fields=['status'], name='lote_produc_status_022c5d_idx'), models.Index(fields=['production_date'], name='lote_produc_product_c610fc_idx'), models.Index(fields=['batch_code'], name='lote_produc_batch_c_d98bf0_idx')],
            },
        ),
    ]
