# Generated by Django 5.2.7 on 2026-01-21 17:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lote_produccion', '0001_initial'),
        ('unidad', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='loteproduccion',
            name='production_manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lotes_gestionados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='loteproduccion',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lotes_produccion', to='unidad.unidad'),
        ),
    ]
