# Generated by Django 5.2.7 on 2026-01-23 03:50

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0001_initial'),
        ('lote_produccion', '0002_initial'),
        ('producto', '0001_initial'),
        ('unidad', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loteproduccion',
            options={'ordering': ['-production_date', '-created_at'], 'verbose_name': 'Lote de Producción', 'verbose_name_plural': 'Lotes de Producción'},
        ),
        migrations.AddField(
            model_name='loteproduccion',
            name='almacen',
            field=models.ForeignKey(default=1, help_text='Almacén donde se fabrica y se registra el inventario', on_delete=django.db.models.deletion.PROTECT, related_name='lotes_produccion', to='almacen.almacen', verbose_name='Almacén'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loteproduccion',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Completado'),
        ),
        migrations.AddField(
            model_name='loteproduccion',
            name='costo_materiales',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Suma de costos de todas las materias primas usadas', max_digits=15, verbose_name='Costo de Materiales'),
        ),
        migrations.AddField(
            model_name='loteproduccion',
            name='costo_unitario_producto',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), help_text='costo_materiales / produced_quantity', max_digits=12, verbose_name='Costo Unitario del Producto'),
        ),
        migrations.AddField(
            model_name='loteproduccion',
            name='observaciones',
            field=models.TextField(blank=True, null=True, verbose_name='Observaciones'),
        ),
        migrations.AlterField(
            model_name='loteproduccion',
            name='batch_code',
            field=models.CharField(max_length=50, unique=True, verbose_name='Código de Lote'),
        ),
        migrations.AlterField(
            model_name='loteproduccion',
            name='produced_quantity',
            field=models.DecimalField(decimal_places=4, max_digits=12, verbose_name='Cantidad Producida'),
        ),
        migrations.AlterField(
            model_name='loteproduccion',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lotes_produccion', to='producto.producto', verbose_name='Producto a Fabricar'),
        ),
        migrations.AlterField(
            model_name='loteproduccion',
            name='production_date',
            field=models.DateField(verbose_name='Fecha de Producción'),
        ),
        migrations.AlterField(
            model_name='loteproduccion',
            name='production_manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lotes_gestionados', to=settings.AUTH_USER_MODEL, verbose_name='Responsable de Producción'),
        ),
        migrations.AlterField(
            model_name='loteproduccion',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('in_progress', 'En Proceso'), ('completed', 'Completado'), ('cancelled', 'Cancelado')], default='pending', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='loteproduccion',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lotes_produccion', to='unidad.unidad', verbose_name='Unidad de Medida'),
        ),
        migrations.AddIndex(
            model_name='loteproduccion',
            index=models.Index(fields=['status'], name='lote_produc_status_022c5d_idx'),
        ),
        migrations.AddIndex(
            model_name='loteproduccion',
            index=models.Index(fields=['production_date'], name='lote_produc_product_c610fc_idx'),
        ),
        migrations.AddIndex(
            model_name='loteproduccion',
            index=models.Index(fields=['batch_code'], name='lote_produc_batch_c_d98bf0_idx'),
        ),
    ]
