# Generated by Django 5.2.7 on 2026-01-26 19:58

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categoria', '0001_initial'),
        ('unidad', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('costo_unitario', models.DecimalField(decimal_places=4, default=0.0, help_text='Último costo unitario de producción o compra', max_digits=10, verbose_name='Costo Unitario')),
                ('stock', models.DecimalField(decimal_places=6, default=0, help_text='Cantidad actual en inventario', max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Stock')),
                ('stock_minimo', models.DecimalField(decimal_places=6, default=0, help_text='Cantidad mínima requerida en inventario para alertas de reabastecimiento', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Stock Mínimo')),
                ('stock_maximo', models.DecimalField(blank=True, decimal_places=6, help_text='Cantidad máxima permitida en inventario (opcional, para control de sobreinventario)', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Stock Máximo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categoria_id', models.ForeignKey(help_text='Categoría del producto terminado', limit_choices_to={'tipo': 'PRODUCT'}, on_delete=django.db.models.deletion.PROTECT, related_name='productos', to='categoria.categoria', verbose_name='Categoría')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='productos', to='unidad.unidad')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'db_table': 'producto',
                'ordering': ['-created_at'],
            },
        ),
    ]
