# Generated by Django 5.2.7 on 2026-01-23 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='stock_maximo',
            field=models.PositiveIntegerField(blank=True, help_text='Cantidad máxima permitida en inventario (opcional, para control de sobreinventario)', null=True, verbose_name='Stock Máximo'),
        ),
        migrations.AddField(
            model_name='producto',
            name='stock_minimo',
            field=models.PositiveIntegerField(default=0, help_text='Cantidad mínima requerida en inventario para alertas de reabastecimiento', verbose_name='Stock Mínimo'),
        ),
    ]
