# Generated by Django 5.2.7 on 2026-01-23 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0002_producto_stock_maximo_producto_stock_minimo'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='costo_unitario',
            field=models.DecimalField(decimal_places=4, default=0.0, help_text='Último costo unitario de producción o compra', max_digits=10, verbose_name='Costo Unitario'),
        ),
    ]
