# Generated by Django 5.2.7 on 2026-01-23 08:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0003_producto_costo_unitario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='stock',
            field=models.DecimalField(decimal_places=4, default=0, help_text='Cantidad actual en inventario', max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Stock'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='stock_maximo',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Cantidad máxima permitida en inventario (opcional, para control de sobreinventario)', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Stock Máximo'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='stock_minimo',
            field=models.DecimalField(decimal_places=4, default=0, help_text='Cantidad mínima requerida en inventario para alertas de reabastecimiento', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Stock Mínimo'),
        ),
    ]
