# Generated by Django 5.2.7 on 2026-01-04 21:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categoria', '0001_initial'),
        ('producto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='categoria_id',
            field=models.ForeignKey(default=1, help_text='Categoría del producto terminado', limit_choices_to={'tipo': 'PRODUCT'}, on_delete=django.db.models.deletion.PROTECT, related_name='productos', to='categoria.categoria', verbose_name='Categoría'),
            preserve_default=False,
        ),
    ]
