# Generated by Django 5.2.7 on 2026-01-26 19:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('proveedor_id', models.CharField(editable=False, help_text='Codigo unico del proveedor (ej: PR000001)', max_length=8, primary_key=True, serialize=False, unique=True, verbose_name='ID Proveedor')),
                ('ruc', models.CharField(help_text='Registro Unico de Contribuyentes (13 digitos)', max_length=13, unique=True, validators=[django.core.validators.RegexValidator(message='El RUC debe tener exactamente 13 digitos', regex='^\\d{13}$')], verbose_name='RUC')),
                ('nombre_empresa', models.CharField(help_text='Razon social o nombre comercial del proveedor', max_length=100, verbose_name='Nombre de la Empresa')),
                ('nombre_contacto', models.CharField(blank=True, help_text='Persona de contacto en la empresa proveedora', max_length=100, null=True, verbose_name='Nombre de Contacto')),
                ('telefono', models.CharField(blank=True, help_text='Numero de telefono principal de contacto', max_length=24, null=True, validators=[django.core.validators.RegexValidator(message='El numero de telefono debe tener entre 9 y 15 digitos', regex='^\\+?1?\\d{9,15}$')], verbose_name='Telefono')),
                ('email', models.EmailField(help_text='Email de contacto del proveedor', max_length=100, validators=[django.core.validators.EmailValidator()], verbose_name='Correo Electronico')),
                ('direccion', models.TextField(blank=True, help_text='Direccion fisica del proveedor', null=True, verbose_name='Direccion')),
                ('tipo_producto', models.CharField(blank=True, help_text='Que productos o servicios provee (ej: Quimicos industriales, Envases)', max_length=200, null=True, verbose_name='Tipo de Producto')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Ultima Actualizacion')),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'db_table': 'proveedor',
                'ordering': ['proveedor_id'],
                'indexes': [models.Index(fields=['ruc'], name='proveedor_ruc_d3b5ec_idx'), models.Index(fields=['nombre_empresa'], name='proveedor_nombre__0d4e51_idx'), models.Index(fields=['email'], name='proveedor_email_9a716e_idx')],
            },
        ),
    ]
