# Generated by Django 5.2.7 on 2025-10-28 05:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proveedor',
            name='activo',
        ),
        migrations.AddField(
            model_name='proveedor',
            name='nombre_contacto',
            field=models.CharField(blank=True, help_text='Persona de contacto en la empresa proveedora', max_length=100, null=True, verbose_name='Nombre de Contacto'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='direccion',
            field=models.TextField(blank=True, help_text='Direccion fisica del proveedor', null=True, verbose_name='Direccion'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='proveedor_id',
            field=models.CharField(editable=False, help_text='Codigo unico del proveedor (ej: PR000001)', max_length=8, primary_key=True, serialize=False, unique=True, verbose_name='ID Proveedor'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='telefono',
            field=models.CharField(blank=True, help_text='Numero de telefono principal de contacto', max_length=24, null=True, validators=[django.core.validators.RegexValidator(message='El numero de telefono debe tener entre 9 y 15 digitos', regex='^\\+?1?\\d{9,15}$')], verbose_name='Telefono'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='tipo_producto',
            field=models.CharField(blank=True, help_text='Que productos o servicios provee (ej: Quimicos industriales, Envases)', max_length=200, null=True, verbose_name='Tipo de Producto'),
        ),
        migrations.AddIndex(
            model_name='proveedor',
            index=models.Index(fields=['email'], name='proveedor_email_9a716e_idx'),
        ),
    ]
