# Generated by Django 5.2.7 on 2025-10-28 01:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente_id', models.CharField(editable=False, help_text='Código único del cliente (autogenerado, prefijo CL)', max_length=8, unique=True, verbose_name='ID Cliente')),
                ('ruc', models.CharField(help_text='Registro Único de Contribuyentes (13 dígitos)', max_length=13, unique=True, validators=[django.core.validators.RegexValidator(message='El RUC debe tener exactamente 13 dígitos', regex='^\\d{13}$')], verbose_name='RUC')),
                ('nombre_empresa', models.CharField(help_text='Razón social o nombre comercial de la empresa', max_length=100, verbose_name='Nombre de la Empresa')),
                ('telefono', models.CharField(blank=True, help_text='Número de teléfono principal de contacto', max_length=24, null=True, validators=[django.core.validators.RegexValidator(message='El número de teléfono debe tener entre 9 y 15 dígitos', regex='^\\+?1?\\d{9,15}$')], verbose_name='Teléfono')),
                ('email', models.EmailField(help_text='Email de contacto de la empresa', max_length=100, validators=[django.core.validators.EmailValidator()], verbose_name='Correo Electrónico')),
                ('direccion', models.TextField(help_text='Dirección completa de la empresa para entregas', verbose_name='Dirección')),
                ('activo', models.BooleanField(default=True, help_text='Indica si el cliente está activo para realizar compras', verbose_name='Cliente Activo')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'db_table': 'cliente',
                'ordering': ['cliente_id'],
                'indexes': [models.Index(fields=['ruc'], name='cliente_ruc_bd3ad2_idx'), models.Index(fields=['nombre_empresa'], name='cliente_nombre__17fd20_idx')],
            },
        ),
    ]
