# Generated by Django 5.2.7 on 2026-01-21 07:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cliente",
            fields=[
                (
                    "cliente_id",
                    models.CharField(
                        editable=False,
                        help_text="Codigo unico autogenerado (formato: CL000001)",
                        max_length=8,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID Cliente",
                    ),
                ),
                (
                    "ruc",
                    models.CharField(
                        max_length=13,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="El RUC debe tener exactamente 13 digitos",
                                regex="^\\d{13}$",
                            )
                        ],
                        verbose_name="RUC",
                    ),
                ),
                (
                    "nombre_empresa",
                    models.CharField(
                        max_length=100, verbose_name="Nombre de la Empresa"
                    ),
                ),
                (
                    "nombre_contacto",
                    models.CharField(
                        blank=True,
                        help_text="Nombre de la persona de contacto en la empresa (opcional)",
                        max_length=100,
                        null=True,
                        verbose_name="Nombre del Contacto",
                    ),
                ),
                (
                    "telefono",
                    models.CharField(
                        blank=True,
                        max_length=24,
                        null=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="El numero de telefono debe tener entre 9 y 15 digitos",
                                regex="^\\+?1?\\d{9,15}$",
                            )
                        ],
                        verbose_name="Telefono",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=100,
                        validators=[django.core.validators.EmailValidator()],
                        verbose_name="Correo Electronico",
                    ),
                ),
                ("direccion", models.TextField(verbose_name="Direccion")),
                (
                    "fecha_registro",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Registro"
                    ),
                ),
                (
                    "fecha_actualizacion",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Ultima Actualizacion"
                    ),
                ),
            ],
            options={
                "verbose_name": "Cliente",
                "verbose_name_plural": "Clientes",
                "db_table": "cliente",
                "ordering": ["cliente_id"],
                "indexes": [
                    models.Index(fields=["ruc"], name="cliente_ruc_bd3ad2_idx"),
                    models.Index(
                        fields=["nombre_empresa"], name="cliente_nombre__17fd20_idx"
                    ),
                ],
            },
        ),
    ]
