# Generated by Django 5.2.7 on 2025-10-28 02:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='id',
        ),
        migrations.AlterField(
            model_name='cliente',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='Cliente Activo'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cliente_id',
            field=models.CharField(editable=False, help_text='Codigo unico autogenerado (formato: CL000001)', max_length=8, primary_key=True, serialize=False, verbose_name='ID Cliente'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='direccion',
            field=models.TextField(verbose_name='Direccion'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='email',
            field=models.EmailField(max_length=100, validators=[django.core.validators.EmailValidator()], verbose_name='Correo Electronico'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True, verbose_name='Ultima Actualizacion'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nombre_empresa',
            field=models.CharField(max_length=100, verbose_name='Nombre de la Empresa'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='ruc',
            field=models.CharField(max_length=13, unique=True, validators=[django.core.validators.RegexValidator(message='El RUC debe tener exactamente 13 digitos', regex='^\\d{13}$')], verbose_name='RUC'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=models.CharField(blank=True, max_length=24, null=True, validators=[django.core.validators.RegexValidator(message='El numero de telefono debe tener entre 9 y 15 digitos', regex='^\\+?1?\\d{9,15}$')], verbose_name='Telefono'),
        ),
    ]
