# Generated by Django 5.2.7 on 2025-10-28 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0002_remove_cliente_id_alter_cliente_activo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='activo',
        ),
        migrations.AddField(
            model_name='cliente',
            name='nombre_contacto',
            field=models.CharField(blank=True, help_text='Nombre de la persona de contacto en la empresa (opcional)', max_length=100, null=True, verbose_name='Nombre del Contacto'),
        ),
    ]
