# Generated by Django 5.2.7 on 2025-10-29 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='rol',
            field=models.CharField(default='Employee', unique=True),
            preserve_default=False,
        ),
    ]
