# Generated by Django 5.2.7 on 2025-11-20 06:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('unidad', '0002_alter_unidad_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='PedidoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_solicitada', models.IntegerField()),
                ('cantidad_recibida', models.IntegerField()),
                ('id_unidad_medida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items_pedido', to='unidad.unidad')),
            ],
        ),
    ]
