# Generated by Django 5.2.7 on 2025-10-22 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Unidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, unique=True)),
                ('simbolo', models.CharField(max_length=10, unique=True)),
                ('factor_conversion', models.FloatField(help_text='Factor de conversión respecto a la unidad base (por ejemplo, 1 g = 1.0, 1 kg = 1000.0)')),
            ],
        ),
    ]
