# Generated by Django 5.2.7 on 2025-10-30 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unidad', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='unidad',
            options={'ordering': ['nombre'], 'verbose_name': 'Unidad', 'verbose_name_plural': 'Unidades'},
        ),
    ]
