# Generated by Django 5.2.7 on 2025-11-20 07:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unidad', '0002_alter_unidad_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='unidad',
            options={'verbose_name': 'Unidad', 'verbose_name_plural': 'Unidades'},
        ),
        migrations.AddField(
            model_name='unidad',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='unidad',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='unidad',
            name='factor_conversion',
            field=models.DecimalField(decimal_places=6, help_text='Factor de conversión respecto a la unidad base', max_digits=10),
        ),
        migrations.AlterField(
            model_name='unidad',
            name='nombre',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='unidad',
            name='simbolo',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterModelTable(
            name='unidad',
            table='unidad',
        ),
    ]
