# Generated by Django 5.2.7 on 2025-11-20 06:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recepcion_material', '0001_initial'),
        ('unidad', '0002_alter_unidad_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecepcionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('lote', models.CharField(max_length=100)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('id_recepcion_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items_recepcion', to='recepcion_material.recepcionmaterial')),
                ('id_unidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items_recepcion', to='unidad.unidad')),
            ],
        ),
    ]
