# Generated by Django 5.2.7 on 2026-01-21 07:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("materia_prima", "0001_initial"),
        ("recepcion_material", "0001_initial"),
        ("unidad", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RecepcionItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cantidad", models.IntegerField()),
                ("lote", models.CharField(max_length=100)),
                ("observaciones", models.TextField(blank=True, null=True)),
                (
                    "precio_compra",
                    models.DecimalField(decimal_places=4, default=0.0, max_digits=12),
                ),
                (
                    "id_recepcion_material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items_recepcion",
                        to="recepcion_material.recepcionmaterial",
                    ),
                ),
                (
                    "id_unidad",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items_recepcion",
                        to="unidad.unidad",
                    ),
                ),
                (
                    "materia_prima",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="items_recepcion",
                        to="materia_prima.materiaprima",
                    ),
                ),
            ],
        ),
    ]
