# Generated by Django 5.2.7 on 2026-01-04 21:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('almacen', '__first__'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kardex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('object_id', models.CharField(max_length=8)),
                ('tipo_movimiento', models.CharField(choices=[('ENTRADA', 'Entrada'), ('SALIDA', 'Salida')], max_length=10)),
                ('motivo', models.CharField(choices=[('COMPRA', 'Compra/Recepción'), ('PRODUCCION', 'Producción'), ('VENTA', 'Venta/Orden Cliente'), ('AJUSTE', 'Ajuste de Inventario')], max_length=20)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=12)),
                ('costo_unitario', models.DecimalField(decimal_places=2, max_digits=12)),
                ('saldo_cantidad', models.DecimalField(decimal_places=2, max_digits=12)),
                ('saldo_costo_total', models.DecimalField(decimal_places=2, max_digits=15)),
                ('almacen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almacen.almacen')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Kardex',
                'verbose_name_plural': 'Kardex',
                'ordering': ['-fecha', '-id'],
            },
        ),
    ]
