# Generated by Django 5.2.7 on 2026-01-05 07:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("almacen", "__first__"),
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Kardex",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fecha",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha del Movimiento"
                    ),
                ),
                ("object_id", models.CharField(max_length=8)),
                (
                    "tipo_movimiento",
                    models.CharField(
                        choices=[("ENTRADA", "Entrada"), ("SALIDA", "Salida")],
                        max_length=10,
                        verbose_name="Tipo de Movimiento",
                    ),
                ),
                (
                    "motivo",
                    models.CharField(
                        choices=[
                            ("COMPRA", "Compra/Recepción"),
                            ("PRODUCCION", "Producción"),
                            ("VENTA", "Venta/Orden Cliente"),
                            ("AJUSTE", "Ajuste de Inventario"),
                            ("DEVOLUCION", "Devolución"),
                        ],
                        max_length=20,
                        verbose_name="Motivo del Movimiento",
                    ),
                ),
                (
                    "cantidad",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        verbose_name="Cantidad del Movimiento",
                    ),
                ),
                (
                    "costo_unitario",
                    models.DecimalField(
                        decimal_places=4, max_digits=12, verbose_name="Costo Unitario"
                    ),
                ),
                (
                    "costo_total",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="cantidad * costo_unitario",
                        max_digits=15,
                        verbose_name="Costo Total del Movimiento",
                    ),
                ),
                (
                    "saldo_cantidad",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        verbose_name="Saldo en Cantidad",
                    ),
                ),
                (
                    "saldo_costo_total",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=15,
                        verbose_name="Saldo en Valor Monetario",
                    ),
                ),
                (
                    "saldo_costo_promedio",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="saldo_costo_total / saldo_cantidad",
                        max_digits=12,
                        verbose_name="Costo Promedio después del Movimiento",
                    ),
                ),
                (
                    "referencia_id",
                    models.CharField(
                        blank=True,
                        help_text="ID de recepción, orden, lote, etc.",
                        max_length=50,
                        null=True,
                        verbose_name="ID de Referencia",
                    ),
                ),
                (
                    "observaciones",
                    models.TextField(
                        blank=True, null=True, verbose_name="Observaciones"
                    ),
                ),
                (
                    "almacen",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="almacen.almacen",
                        verbose_name="Almacén",
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        limit_choices_to={"model__in": ("materiaprima", "producto")},
                        on_delete=django.db.models.deletion.PROTECT,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario que registró el movimiento",
                    ),
                ),
            ],
            options={
                "verbose_name": "Kardex",
                "verbose_name_plural": "Kardex",
                "ordering": ["-fecha", "-id"],
                "indexes": [
                    models.Index(
                        fields=["content_type", "object_id"],
                        name="inventario__content_144512_idx",
                    ),
                    models.Index(
                        fields=["almacen"], name="inventario__almacen_7f009b_idx"
                    ),
                    models.Index(fields=["fecha"], name="inventario__fecha_6586a6_idx"),
                    models.Index(
                        fields=["tipo_movimiento"],
                        name="inventario__tipo_mo_18c5dc_idx",
                    ),
                ],
            },
        ),
    ]
