# Generated by Django 5.2.7 on 2026-01-21 07:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("inventario", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="kardex",
            name="usuario",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Usuario que registró el movimiento",
            ),
        ),
        migrations.AddIndex(
            model_name="kardex",
            index=models.Index(
                fields=["content_type", "object_id"],
                name="inventario__content_144512_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="kardex",
            index=models.Index(
                fields=["almacen"], name="inventario__almacen_7f009b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="kardex",
            index=models.Index(fields=["fecha"], name="inventario__fecha_6586a6_idx"),
        ),
        migrations.AddIndex(
            model_name="kardex",
            index=models.Index(
                fields=["tipo_movimiento"], name="inventario__tipo_mo_18c5dc_idx"
            ),
        ),
    ]
