# Generated by Django 5.2.7 on 2026-01-23 06:53

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0001_initial'),
        ('cliente', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('inventario', '0002_initial'),
        ('orden_cliente', '0001_initial'),
        ('producto', '0003_producto_costo_unitario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AjusteInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha del Ajuste')),
                ('object_id', models.CharField(max_length=8)),
                ('tipo_ajuste', models.CharField(choices=[('POSITIVO', 'Ajuste Positivo (+ añadir)'), ('NEGATIVO', 'Ajuste Negativo (- quitar)')], max_length=10, verbose_name='Tipo de Ajuste')),
                ('cantidad', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='Cantidad Ajustada')),
                ('costo_unitario', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='Costo Unitario')),
                ('motivo', models.TextField(help_text='Explicación del ajuste', verbose_name='Motivo del Ajuste')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('almacen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='almacen.almacen', verbose_name='Almacén')),
                ('content_type', models.ForeignKey(limit_choices_to={'model__in': ('materiaprima', 'producto')}, on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype')),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Responsable')),
            ],
            options={
                'verbose_name': 'Ajuste de Inventario',
                'verbose_name_plural': 'Ajustes de Inventario',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Devolucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Devolución')),
                ('cantidad', models.PositiveIntegerField(verbose_name='Cantidad Devuelta')),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio Unitario')),
                ('total', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Total Devolución')),
                ('motivo', models.TextField(verbose_name='Motivo de Devolución')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente de Procesamiento'), ('APROBADA', 'Aprobada'), ('RECHAZADA', 'Rechazada'), ('PROCESADA', 'Procesada')], default='PENDIENTE', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('almacen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='almacen.almacen', verbose_name='Almacén')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cliente.cliente', verbose_name='Cliente')),
                ('orden_original', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orden_cliente.ordencliente', verbose_name='Orden Original')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='producto.producto', verbose_name='Producto')),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Responsable')),
            ],
            options={
                'verbose_name': 'Devolución',
                'verbose_name_plural': 'Devoluciones',
                'ordering': ['-fecha'],
            },
        ),
    ]
